from pyhop_anytime import *

strips_sat_x_1_state = State('strips_sat_x_1_state')
strips_sat_x_1_state.calibration_target = {('instrument0','star3'):True,('instrument1','groundstation0'):True,('instrument10','star2'):True,('instrument11','star3'):True,('instrument12','groundstation4'):True,('instrument13','star2'):True,('instrument14','star3'):True,('instrument15','groundstation4'):True,('instrument16','groundstation0'):True,('instrument17','groundstation4'):True,('instrument18','star3'):True,('instrument19','star2'):True,('instrument2','groundstation1'):True,('instrument20','groundstation4'):True,('instrument21','star2'):True,('instrument22','groundstation1'):True,('instrument3','groundstation4'):True,('instrument4','star3'):True,('instrument5','groundstation4'):True,('instrument6','groundstation1'):True,('instrument7','star3'):True,('instrument8','groundstation0'):True,('instrument9','star3'):True}
strips_sat_x_1_state.on_board = {('instrument0','satellite0'):True,('instrument1','satellite0'):True,('instrument10','satellite4'):True,('instrument11','satellite5'):True,('instrument12','satellite5'):True,('instrument13','satellite5'):True,('instrument14','satellite6'):True,('instrument15','satellite6'):True,('instrument16','satellite6'):True,('instrument17','satellite7'):True,('instrument18','satellite7'):True,('instrument19','satellite8'):True,('instrument2','satellite0'):True,('instrument20','satellite8'):True,('instrument21','satellite8'):True,('instrument22','satellite9'):True,('instrument3','satellite1'):True,('instrument4','satellite1'):True,('instrument5','satellite1'):True,('instrument6','satellite2'):True,('instrument7','satellite3'):True,('instrument8','satellite4'):True,('instrument9','satellite4'):True}
strips_sat_x_1_state.pointing = {('satellite0','star15'):True,('satellite1','planet10'):True,('satellite2','star24'):True,('satellite3','phenomenon9'):True,('satellite4','planet19'):True,('satellite5','planet10'):True,('satellite6','planet11'):True,('satellite7','planet11'):True,('satellite8','groundstation4'):True,('satellite9','planet11'):True}
strips_sat_x_1_state.power_avail = {'satellite0':True,'satellite1':True,'satellite2':True,'satellite3':True,'satellite4':True,'satellite5':True,'satellite6':True,'satellite7':True,'satellite8':True,'satellite9':True}
strips_sat_x_1_state.supports = {('instrument0','infrared4'):True,('instrument1','spectrograph3'):True,('instrument10','image0'):True,('instrument10','image2'):True,('instrument10','spectrograph3'):True,('instrument11','image0'):True,('instrument12','image0'):True,('instrument12','infrared4'):True,('instrument13','spectrograph3'):True,('instrument14','image0'):True,('instrument14','spectrograph3'):True,('instrument14','thermograph1'):True,('instrument15','image0'):True,('instrument15','image2'):True,('instrument15','thermograph1'):True,('instrument16','image2'):True,('instrument16','spectrograph3'):True,('instrument17','image0'):True,('instrument17','image2'):True,('instrument17','thermograph1'):True,('instrument18','image2'):True,('instrument18','thermograph1'):True,('instrument19','infrared4'):True,('instrument19','thermograph1'):True,('instrument2','image0'):True,('instrument2','image2'):True,('instrument2','thermograph1'):True,('instrument20','thermograph1'):True,('instrument21','thermograph1'):True,('instrument22','infrared4'):True,('instrument22','spectrograph3'):True,('instrument22','thermograph1'):True,('instrument3','image0'):True,('instrument3','thermograph1'):True,('instrument4','image2'):True,('instrument4','thermograph1'):True,('instrument5','image2'):True,('instrument5','spectrograph3'):True,('instrument5','thermograph1'):True,('instrument6','image0'):True,('instrument7','infrared4'):True,('instrument8','spectrograph3'):True,('instrument9','image0'):True,('instrument9','image2'):True,('instrument9','thermograph1'):True}
strips_sat_x_1_state.calibrated = {}
strips_sat_x_1_state.have_image = {}
strips_sat_x_1_state.power_on = {}

strips_sat_x_1_goals = State('strips_sat_x_1_goals')
strips_sat_x_1_goals.have_image = {('phenomenon17','infrared4'):True,('phenomenon18','spectrograph3'):True,('phenomenon23','image0'):True,('phenomenon5','thermograph1'):True,('phenomenon9','image2'):True,('planet10','image0'):True,('planet11','infrared4'):True,('planet21','thermograph1'):True,('planet22','image2'):True,('planet6','infrared4'):True,('planet7','image0'):True,('planet8','thermograph1'):True,('star12','image0'):True,('star13','image0'):True,('star14','thermograph1'):True,('star15','image0'):True,('star16','thermograph1'):True,('star20','image0'):True,('star24','infrared4'):True}
strips_sat_x_1_goals.pointing = {('satellite5','planet6'):True,('satellite7','star3'):True,('satellite8','star15'):True,('satellite9','star16'):True}

