from pyhop_anytime import *

strips_sat_x_1_state = State('strips_sat_x_1_state')
strips_sat_x_1_state.calibration_target = {('instrument0','groundstation0'):True,('instrument1','star3'):True,('instrument10','groundstation0'):True,('instrument11','groundstation0'):True,('instrument12','star1'):True,('instrument13','star3'):True,('instrument14','groundstation2'):True,('instrument15','groundstation0'):True,('instrument16','groundstation2'):True,('instrument17','star1'):True,('instrument18','star4'):True,('instrument2','star4'):True,('instrument3','groundstation2'):True,('instrument4','star1'):True,('instrument5','groundstation2'):True,('instrument6','groundstation2'):True,('instrument7','star3'):True,('instrument8','groundstation2'):True,('instrument9','star3'):True}
strips_sat_x_1_state.on_board = {('instrument0','satellite0'):True,('instrument1','satellite0'):True,('instrument10','satellite5'):True,('instrument11','satellite5'):True,('instrument12','satellite5'):True,('instrument13','satellite6'):True,('instrument14','satellite6'):True,('instrument15','satellite6'):True,('instrument16','satellite7'):True,('instrument17','satellite7'):True,('instrument18','satellite7'):True,('instrument2','satellite1'):True,('instrument3','satellite1'):True,('instrument4','satellite2'):True,('instrument5','satellite2'):True,('instrument6','satellite3'):True,('instrument7','satellite4'):True,('instrument8','satellite4'):True,('instrument9','satellite4'):True}
strips_sat_x_1_state.pointing = {('satellite0','star19'):True,('satellite1','star18'):True,('satellite2','star19'):True,('satellite3','star4'):True,('satellite4','phenomenon9'):True,('satellite5','planet6'):True,('satellite6','planet17'):True,('satellite7','planet11'):True}
strips_sat_x_1_state.power_avail = {'satellite0':True,'satellite1':True,'satellite2':True,'satellite3':True,'satellite4':True,'satellite5':True,'satellite6':True,'satellite7':True}
strips_sat_x_1_state.supports = {('instrument0','image1'):True,('instrument0','thermograph4'):True,('instrument1','spectrograph2'):True,('instrument1','thermograph3'):True,('instrument10','infrared0'):True,('instrument10','spectrograph2'):True,('instrument10','thermograph4'):True,('instrument11','infrared0'):True,('instrument12','infrared0'):True,('instrument13','infrared0'):True,('instrument13','thermograph3'):True,('instrument14','spectrograph2'):True,('instrument15','thermograph4'):True,('instrument16','thermograph4'):True,('instrument17','spectrograph2'):True,('instrument18','thermograph4'):True,('instrument2','spectrograph2'):True,('instrument3','image1'):True,('instrument3','spectrograph2'):True,('instrument4','spectrograph2'):True,('instrument4','thermograph3'):True,('instrument4','thermograph4'):True,('instrument5','image1'):True,('instrument5','infrared0'):True,('instrument5','thermograph3'):True,('instrument6','infrared0'):True,('instrument6','spectrograph2'):True,('instrument7','spectrograph2'):True,('instrument7','thermograph3'):True,('instrument8','image1'):True,('instrument9','infrared0'):True}
strips_sat_x_1_state.calibrated = {}
strips_sat_x_1_state.have_image = {}
strips_sat_x_1_state.power_on = {}

strips_sat_x_1_goals = State('strips_sat_x_1_goals')
strips_sat_x_1_goals.have_image = {('phenomenon10','image1'):True,('phenomenon16','image1'):True,('phenomenon5','spectrograph2'):True,('phenomenon9','infrared0'):True,('planet11','image1'):True,('planet14','thermograph4'):True,('planet17','thermograph3'):True,('planet20','image1'):True,('planet21','infrared0'):True,('planet22','image1'):True,('planet23','thermograph3'):True,('planet24','infrared0'):True,('planet6','spectrograph2'):True,('planet7','infrared0'):True,('star12','thermograph3'):True,('star13','thermograph3'):True,('star15','thermograph4'):True,('star18','image1'):True}
strips_sat_x_1_goals.pointing = {('satellite0','star19'):True,('satellite1','planet22'):True,('satellite2','star13'):True,('satellite3','planet14'):True,('satellite5','planet24'):True,('satellite7','star3'):True}

