from pyhop_anytime import *

strips_sat_x_1_state = State('strips_sat_x_1_state')
strips_sat_x_1_state.calibration_target = {('instrument0','groundstation0'):True,('instrument1','star3'):True,('instrument10','star3'):True,('instrument11','star1'):True,('instrument12','groundstation0'):True,('instrument13','star1'):True,('instrument14','groundstation2'):True,('instrument15','groundstation4'):True,('instrument16','star1'):True,('instrument17','groundstation0'):True,('instrument18','star1'):True,('instrument19','groundstation4'):True,('instrument2','groundstation0'):True,('instrument20','star1'):True,('instrument21','star1'):True,('instrument22','groundstation0'):True,('instrument23','star3'):True,('instrument3','groundstation4'):True,('instrument4','groundstation2'):True,('instrument5','groundstation4'):True,('instrument6','groundstation2'):True,('instrument7','groundstation0'):True,('instrument8','groundstation4'):True,('instrument9','star1'):True}
strips_sat_x_1_state.on_board = {('instrument0','satellite0'):True,('instrument1','satellite1'):True,('instrument10','satellite4'):True,('instrument11','satellite5'):True,('instrument12','satellite6'):True,('instrument13','satellite6'):True,('instrument14','satellite6'):True,('instrument15','satellite7'):True,('instrument16','satellite8'):True,('instrument17','satellite8'):True,('instrument18','satellite9'):True,('instrument19','satellite9'):True,('instrument2','satellite1'):True,('instrument20','satellite10'):True,('instrument21','satellite10'):True,('instrument22','satellite10'):True,('instrument23','satellite11'):True,('instrument3','satellite2'):True,('instrument4','satellite2'):True,('instrument5','satellite2'):True,('instrument6','satellite3'):True,('instrument7','satellite3'):True,('instrument8','satellite3'):True,('instrument9','satellite4'):True}
strips_sat_x_1_state.pointing = {('satellite0','planet5'):True,('satellite1','planet5'):True,('satellite10','star22'):True,('satellite11','star8'):True,('satellite2','star21'):True,('satellite3','star21'):True,('satellite4','star22'):True,('satellite5','groundstation2'):True,('satellite6','phenomenon20'):True,('satellite7','planet12'):True,('satellite8','phenomenon23'):True,('satellite9','phenomenon20'):True}
strips_sat_x_1_state.power_avail = {'satellite0':True,'satellite1':True,'satellite10':True,'satellite11':True,'satellite2':True,'satellite3':True,'satellite4':True,'satellite5':True,'satellite6':True,'satellite7':True,'satellite8':True,'satellite9':True}
strips_sat_x_1_state.supports = {('instrument0','infrared3'):True,('instrument1','image0'):True,('instrument1','infrared2'):True,('instrument10','image0'):True,('instrument10','image4'):True,('instrument11','infrared2'):True,('instrument12','image4'):True,('instrument13','image4'):True,('instrument14','infrared2'):True,('instrument14','thermograph1'):True,('instrument15','image0'):True,('instrument15','thermograph1'):True,('instrument16','image0'):True,('instrument16','infrared2'):True,('instrument17','infrared3'):True,('instrument18','image4'):True,('instrument18','infrared2'):True,('instrument18','thermograph1'):True,('instrument19','infrared3'):True,('instrument2','image0'):True,('instrument2','thermograph1'):True,('instrument20','infrared2'):True,('instrument21','image0'):True,('instrument21','thermograph1'):True,('instrument22','thermograph1'):True,('instrument23','image4'):True,('instrument23','infrared2'):True,('instrument23','thermograph1'):True,('instrument3','infrared2'):True,('instrument3','infrared3'):True,('instrument4','infrared2'):True,('instrument4','infrared3'):True,('instrument4','thermograph1'):True,('instrument5','thermograph1'):True,('instrument6','image0'):True,('instrument6','infrared2'):True,('instrument7','image0'):True,('instrument7','infrared3'):True,('instrument8','image0'):True,('instrument8','image4'):True,('instrument8','infrared2'):True,('instrument9','infrared3'):True}
strips_sat_x_1_state.calibrated = {}
strips_sat_x_1_state.have_image = {}
strips_sat_x_1_state.power_on = {}

strips_sat_x_1_goals = State('strips_sat_x_1_goals')
strips_sat_x_1_goals.have_image = {('phenomenon14','infrared2'):True,('phenomenon15','infrared2'):True,('phenomenon17','thermograph1'):True,('phenomenon23','infrared3'):True,('phenomenon24','infrared3'):True,('phenomenon9','image4'):True,('planet11','image4'):True,('planet12','thermograph1'):True,('planet13','infrared3'):True,('planet16','infrared2'):True,('planet5','image0'):True,('planet6','image4'):True,('planet7','image4'):True,('star10','thermograph1'):True,('star18','image4'):True,('star21','thermograph1'):True,('star22','image4'):True}
strips_sat_x_1_goals.pointing = {('satellite1','star22'):True,('satellite4','phenomenon20'):True,('satellite8','planet16'):True}

