from pyhop_anytime import *

strips_sat_x_1_state = State('strips_sat_x_1_state')
strips_sat_x_1_state.calibration_target = {('instrument0','star2'):True,('instrument1','star4'):True,('instrument10','star4'):True,('instrument11','groundstation3'):True,('instrument12','groundstation3'):True,('instrument13','star4'):True,('instrument14','groundstation3'):True,('instrument15','star2'):True,('instrument16','star4'):True,('instrument17','star0'):True,('instrument18','groundstation1'):True,('instrument19','groundstation3'):True,('instrument2','star4'):True,('instrument20','groundstation1'):True,('instrument21','star2'):True,('instrument22','star4'):True,('instrument23','star2'):True,('instrument24','star2'):True,('instrument25','star2'):True,('instrument26','star4'):True,('instrument27','groundstation3'):True,('instrument28','groundstation1'):True,('instrument3','star0'):True,('instrument4','groundstation3'):True,('instrument5','groundstation3'):True,('instrument6','groundstation3'):True,('instrument7','groundstation1'):True,('instrument8','star2'):True,('instrument9','star4'):True}
strips_sat_x_1_state.on_board = {('instrument0','satellite0'):True,('instrument1','satellite0'):True,('instrument10','satellite1'):True,('instrument11','satellite1'):True,('instrument12','satellite1'):True,('instrument13','satellite1'):True,('instrument14','satellite1'):True,('instrument15','satellite1'):True,('instrument16','satellite2'):True,('instrument17','satellite2'):True,('instrument18','satellite2'):True,('instrument19','satellite2'):True,('instrument2','satellite0'):True,('instrument20','satellite3'):True,('instrument21','satellite3'):True,('instrument22','satellite4'):True,('instrument23','satellite4'):True,('instrument24','satellite4'):True,('instrument25','satellite4'):True,('instrument26','satellite4'):True,('instrument27','satellite4'):True,('instrument28','satellite4'):True,('instrument3','satellite0'):True,('instrument4','satellite0'):True,('instrument5','satellite0'):True,('instrument6','satellite0'):True,('instrument7','satellite0'):True,('instrument8','satellite0'):True,('instrument9','satellite0'):True}
strips_sat_x_1_state.pointing = {('satellite0','groundstation1'):True,('satellite1','phenomenon19'):True,('satellite2','phenomenon14'):True,('satellite3','star10'):True,('satellite4','star16'):True}
strips_sat_x_1_state.power_avail = {'satellite0':True,'satellite1':True,'satellite2':True,'satellite3':True,'satellite4':True}
strips_sat_x_1_state.supports = {('instrument0','image3'):True,('instrument1','infrared9'):True,('instrument10','infrared1'):True,('instrument10','spectrograph6'):True,('instrument10','thermograph8'):True,('instrument11','image4'):True,('instrument11','infrared1'):True,('instrument11','thermograph7'):True,('instrument12','infrared5'):True,('instrument12','infrared9'):True,('instrument12','thermograph8'):True,('instrument13','image2'):True,('instrument13','infrared1'):True,('instrument14','image3'):True,('instrument15','thermograph7'):True,('instrument16','image2'):True,('instrument16','infrared9'):True,('instrument17','infrared5'):True,('instrument18','infrared9'):True,('instrument19','image2'):True,('instrument19','infrared5'):True,('instrument2','image2'):True,('instrument2','image4'):True,('instrument2','thermograph8'):True,('instrument20','image2'):True,('instrument20','image3'):True,('instrument20','image4'):True,('instrument21','image3'):True,('instrument21','infrared5'):True,('instrument21','thermograph8'):True,('instrument22','infrared5'):True,('instrument22','thermograph8'):True,('instrument23','image3'):True,('instrument23','thermograph8'):True,('instrument24','thermograph8'):True,('instrument25','infrared5'):True,('instrument26','image3'):True,('instrument27','image2'):True,('instrument27','infrared9'):True,('instrument28','image4'):True,('instrument28','spectrograph0'):True,('instrument28','thermograph7'):True,('instrument3','infrared9'):True,('instrument4','image3'):True,('instrument4','thermograph8'):True,('instrument5','image4'):True,('instrument5','infrared9'):True,('instrument6','infrared1'):True,('instrument7','spectrograph6'):True,('instrument7','thermograph8'):True,('instrument8','infrared9'):True,('instrument8','spectrograph0'):True,('instrument8','thermograph7'):True,('instrument9','thermograph7'):True}
strips_sat_x_1_state.calibrated = {}
strips_sat_x_1_state.have_image = {}
strips_sat_x_1_state.power_on = {}

strips_sat_x_1_goals = State('strips_sat_x_1_goals')
strips_sat_x_1_goals.have_image = {('phenomenon12','image4'):True,('phenomenon14','thermograph7'):True,('phenomenon19','image2'):True,('phenomenon19','image4'):True,('phenomenon21','image2'):True,('phenomenon21','image4'):True,('phenomenon21','thermograph7'):True,('phenomenon5','image3'):True,('phenomenon5','spectrograph0'):True,('phenomenon5','thermograph8'):True,('phenomenon8','infrared5'):True,('phenomenon8','spectrograph6'):True,('phenomenon8','thermograph7'):True,('planet13','image2'):True,('planet13','infrared5'):True,('planet13','spectrograph6'):True,('planet15','image3'):True,('planet18','infrared5'):True,('planet18','infrared9'):True,('planet18','thermograph7'):True,('planet22','image2'):True,('planet22','spectrograph6'):True,('planet7','image2'):True,('planet7','infrared5'):True,('planet7','spectrograph6'):True,('planet9','spectrograph6'):True,('star10','spectrograph6'):True,('star11','image3'):True,('star11','image4'):True,('star11','thermograph7'):True,('star16','image3'):True,('star16','image4'):True,('star20','spectrograph0'):True,('star23','image2'):True,('star23','infrared9'):True,('star24','infrared5'):True,('star24','spectrograph6'):True,('star6','image3'):True,('star6','spectrograph0'):True,('star6','spectrograph6'):True}
strips_sat_x_1_goals.pointing = {('satellite1','phenomenon19'):True}

