from pyhop_anytime import *

strips_sat_x_1_state = State('strips_sat_x_1_state')
strips_sat_x_1_state.calibration_target = {('instrument0','groundstation0'):True,('instrument1','star3'):True,('instrument10','groundstation4'):True,('instrument11','star2'):True,('instrument12','star3'):True,('instrument13','star2'):True,('instrument14','groundstation4'):True,('instrument15','star1'):True,('instrument16','star2'):True,('instrument17','groundstation0'):True,('instrument18','star2'):True,('instrument19','star3'):True,('instrument2','star1'):True,('instrument20','star2'):True,('instrument21','groundstation4'):True,('instrument22','star2'):True,('instrument23','star3'):True,('instrument24','groundstation0'):True,('instrument3','star1'):True,('instrument4','star3'):True,('instrument5','groundstation4'):True,('instrument6','star3'):True,('instrument7','star2'):True,('instrument8','star1'):True,('instrument9','star3'):True}
strips_sat_x_1_state.on_board = {('instrument0','satellite0'):True,('instrument1','satellite0'):True,('instrument10','satellite2'):True,('instrument11','satellite2'):True,('instrument12','satellite2'):True,('instrument13','satellite2'):True,('instrument14','satellite3'):True,('instrument15','satellite3'):True,('instrument16','satellite3'):True,('instrument17','satellite3'):True,('instrument18','satellite3'):True,('instrument19','satellite3'):True,('instrument2','satellite0'):True,('instrument20','satellite3'):True,('instrument21','satellite3'):True,('instrument22','satellite4'):True,('instrument23','satellite4'):True,('instrument24','satellite4'):True,('instrument3','satellite1'):True,('instrument4','satellite1'):True,('instrument5','satellite1'):True,('instrument6','satellite1'):True,('instrument7','satellite1'):True,('instrument8','satellite2'):True,('instrument9','satellite2'):True}
strips_sat_x_1_state.pointing = {('satellite0','planet21'):True,('satellite1','planet21'):True,('satellite2','phenomenon5'):True,('satellite3','phenomenon20'):True,('satellite4','star14'):True}
strips_sat_x_1_state.power_avail = {'satellite0':True,'satellite1':True,'satellite2':True,'satellite3':True,'satellite4':True}
strips_sat_x_1_state.supports = {('instrument0','image4'):True,('instrument0','infrared2'):True,('instrument1','spectrograph0'):True,('instrument10','image4'):True,('instrument10','image5'):True,('instrument10','infrared7'):True,('instrument11','infrared2'):True,('instrument12','thermograph1'):True,('instrument13','infrared3'):True,('instrument14','infrared2'):True,('instrument14','thermograph1'):True,('instrument15','infrared2'):True,('instrument16','image4'):True,('instrument16','spectrograph6'):True,('instrument17','image4'):True,('instrument17','image5'):True,('instrument17','infrared7'):True,('instrument18','image4'):True,('instrument18','spectrograph6'):True,('instrument19','infrared3'):True,('instrument19','infrared7'):True,('instrument19','spectrograph6'):True,('instrument2','infrared3'):True,('instrument2','spectrograph0'):True,('instrument2','thermograph1'):True,('instrument20','infrared2'):True,('instrument20','infrared3'):True,('instrument21','infrared2'):True,('instrument21','thermograph1'):True,('instrument22','image5'):True,('instrument22','thermograph1'):True,('instrument23','infrared7'):True,('instrument23','thermograph1'):True,('instrument24','infrared3'):True,('instrument24','spectrograph0'):True,('instrument3','image5'):True,('instrument3','thermograph1'):True,('instrument4','spectrograph0'):True,('instrument5','spectrograph0'):True,('instrument5','spectrograph6'):True,('instrument5','thermograph1'):True,('instrument6','image5'):True,('instrument6','infrared7'):True,('instrument7','spectrograph0'):True,('instrument7','spectrograph6'):True,('instrument7','thermograph1'):True,('instrument8','infrared3'):True,('instrument8','infrared7'):True,('instrument9','spectrograph0'):True}
strips_sat_x_1_state.calibrated = {}
strips_sat_x_1_state.have_image = {}
strips_sat_x_1_state.power_on = {}

strips_sat_x_1_goals = State('strips_sat_x_1_goals')
strips_sat_x_1_goals.have_image = {('phenomenon11','infrared2'):True,('phenomenon13','infrared2'):True,('phenomenon13','infrared7'):True,('phenomenon20','spectrograph0'):True,('phenomenon24','image5'):True,('phenomenon24','spectrograph6'):True,('phenomenon5','image4'):True,('phenomenon5','infrared7'):True,('phenomenon7','thermograph1'):True,('planet15','infrared2'):True,('planet17','image4'):True,('planet17','image5'):True,('planet21','image5'):True,('planet21','infrared3'):True,('planet22','infrared2'):True,('planet9','spectrograph0'):True,('planet9','spectrograph6'):True,('star10','infrared3'):True,('star10','spectrograph6'):True,('star12','spectrograph6'):True,('star12','thermograph1'):True,('star14','infrared2'):True,('star16','image4'):True,('star18','infrared2'):True,('star19','infrared3'):True,('star19','thermograph1'):True,('star23','infrared2'):True}
strips_sat_x_1_goals.pointing = {('satellite0','planet17'):True}

